website/forms/profiles.py
from flask_wtf import FlaskForm

class EditProfileForm(FlaskForm):
    pass
    # username = StringField("Username", validators=[DataRequired(), Length(min=4, max=12)], render_kw={"placeholder": "Enter your username"})
    # fullname = StringField("Full Name", validators=[Length(min=4, max=16)], render_kw={"placeholder": "Enter your full name"})
    # bio = TextAreaField("Bio", render_kw={"placeholder": "Enter your bio"})
    # profile_pic = FileField("Profile Picture", validators=[FileAllowed(["jpg", "jpeg", "png"])])
    # submit = SubmitField("Update Profile")

website/forms/tournaments.py
from flask_wtf import FlaskForm
from wtforms import ValidationError, StringField, SubmitField, IntegerField, SelectField
from wtforms_sqlalchemy.fields import QuerySelectMultipleField
from wtforms.validators import InputRequired, Length, NumberRange
from math import ceil, log

from website.models import Member

class MinTwoParticipants(object):
    """
    Validates that there are at least 2 participants selected.
    """
    def __init__(self):
        self.message = "Select at least 2 participants."

    def __call__(self, form, field):
        if len(field.data) < 2:
            raise ValidationError(self.message)

class CreateTournamentForm(FlaskForm):
    title = StringField("Title", validators=[InputRequired(), Length(min=1, max=31)], render_kw={"placeholder": "Enter title name"})
    time_control_minutes = IntegerField("Time Control Minutes", validators=[NumberRange(min=0, max=300)], render_kw={"placeholder": "mins"})
    time_control_seconds = IntegerField("Time Control Seconds", validators=[NumberRange(min=0, max=59)], render_kw={"placeholder": "secs"})
    time_control_increment = IntegerField("Time Control Increment", validators=[NumberRange(min=0, max=59)], render_kw={"placeholder": "inc"})
    pairing_system = SelectField("Pairing System", choices=[
        ("Swiss System", "Swiss System"),
        ("Round-Robin", "Round-Robin"),
        ("Elimination", "Elimination"),
        ("Custom", "Custom")
    ], validators=[InputRequired()])
    number_of_rounds = IntegerField("Number of Rounds", validators=[InputRequired(), NumberRange(min=1)], render_kw={"placeholder": "Enter # of rounds"})
    participants = QuerySelectMultipleField("Participants", query_factory=lambda: Member.query.filter_by(is_active=True).order_by(Member.full_name).all(), allow_blank=True, get_label="full_name", validators=[MinTwoParticipants()])
    submit = SubmitField("Create Tournament")

    def validate_time_controls(self, field):
        if self.time_control_minutes.data == 0 and self.time_control_seconds.data == 0:
            raise ValidationError("Time Control Minutes or Time Control Seconds must be greater than zero.")

    def validate_number_of_rounds(self, field):
        number_of_participants = len(self.participants.data)
        if self.pairing_system.data == "Swiss System":
            max_rounds = ceil(log(number_of_participants, 2))
            if field.data > max_rounds:
                raise ValidationError(f"Maximum rounds for {number_of_participants} participant(s) in {self.pairing_system.data} is {max_rounds}.")
        if self.pairing_system.data == "Round-Robin":
            max_rounds = number_of_participants - 1
            if field.data > max_rounds:
                raise ValidationError(f"Maximum rounds for {number_of_participants} participant(s) in {self.pairing_system.data} is {max_rounds}.")
        if self.pairing_system.data == "Elimination":
            max_rounds = ceil(log(number_of_participants, 2))
            if field.data > max_rounds:
                raise ValidationError(f"Maximum rounds for {number_of_participants} participant(s) in {self.pairing_system.data} is {max_rounds}.")

class EditTournamentForm(FlaskForm):
    pass

class StartTournamentForm(FlaskForm):
    pass

class EndTournamentForm(FlaskForm):
    pass

website/routes/views.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session, jsonify
from flask_login import login_required
from sqlalchemy import func, case

from website import db
from website.models import User, Member, Match, Tournament, Participant
from website.forms.tournaments import CreateTournamentForm
from website import utils

views = Blueprint("views", __name__)

@views.route("/set_timezone_offset", methods=["POST"])
def set_timezone_offset():
    data = request.get_json()
    session["timezoneOffset"] = data.get("timezoneOffset")

    return jsonify({"message": "Timezone offset received"}), 200

@views.app_context_processor
def inject_members():
    aside_ctx = {
        "members": Member.query.order_by(Member.rating.desc()).limit(5)
    }
    return {"aside_ctx": aside_ctx}

@views.route("/")
def index():
    return render_template("index.html")

@views.route("/leaderboard")
def leaderboard():
    return redirect(url_for("views.leaderboard_top_rated"))

@views.route("/leaderboard/top-rated")
def leaderboard_top_rated():
    page = request.args.get("page", 1, type=int)
    members = Member.query.order_by(Member.rating.desc(), Member.full_name).paginate(page=page, per_page=15)

    return render_template("leaderboard-top-rated.html", title="Leaderboard", members=members, page=page)

@views.route("/leaderboard/win-rate")
def leaderboard_win_rate():
    page = request.args.get("page", 1, type=int)
    members = Member.query\
        .outerjoin(Match, ((Match.white_player_id == Member.id) | (Match.black_player_id == Member.id)))\
        .group_by(Member.id)\
        .order_by(Member.win_rate.desc(), Member.draw_rate.desc(), Member.full_name)\
        .paginate(page=page, per_page=15)

    return render_template("leaderboard-win-rate.html", title="Leaderboard", members=members, page=page)

@views.route("/leaderboard/tournaments-participated")
def leaderboard_tournaments_participated():
    page = request.args.get("page", 1, type=int)
    members = Member.query.outerjoin(Member.tournaments).group_by(Member.id).order_by(func.count(Tournament.id).desc()).paginate(page=page, per_page=15)

    return render_template("leaderboard-tournaments-participated.html", title="Leaderboard", members=members, page=page)

@views.route("/tournaments")
def tournaments():
    tournaments = Tournament.query.order_by(Tournament.tournament_date.desc()).all()
    timezone_offset = session.get("timezoneOffset")

    return render_template("tournaments.html", title="Tournaments", tournaments=tournaments, timezone_offset=timezone_offset, utils=utils)

@views.route("/tournaments/create", methods=["GET", "POST"])
def tournaments_create():
    form = CreateTournamentForm()

    if form.validate_on_submit():
        new_tournament = Tournament(
            title=form.title.data,
            time_control_duration=60 * form.time_control_minutes.data + form.time_control_seconds.data,
            time_control_increment=form.time_control_increment.data,
            matching_system=form.matching_system.data,
            number_of_rounds=form.number_of_rounds.data
        )

        db.session.add(new_tournament)
        db.session.commit()

        for member in form.participants.data:
            member_id = member.id
            participant = Participant(tournament_id=new_tournament.id, member_id=member_id)
            db.session.add(participant)
        
        db.session.commit()

        flash("Tournament created successfully!", "success")
        return redirect(url_for("views.tournaments"))

    return render_template("tournaments-create.html", title="Create Tournament", form=form)

@views.route("/tournament/<int:tournament_id>")
def tournament(tournament_id):
    tournament = Tournament.query.get_or_404(tournament_id)

    return render_template("tournament.html", title=tournament.title, tournament=tournament)

@views.route("/<string:user_id>")
@login_required
def profile(user_id):
    user = User.query.get(user_id)
    return render_template("profile.html", title=f"Profile | {user.fullname}", user=user)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='images/logo.jpg') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <script src="{{ url_for('static', filename='script.js') }}" defer></script>
    {% if title %}
        <title>{{ title }} - Chess Club IGS</title>
    {% else %}
        <title>Chess Club IGS</title>
    {% endif %}
</head>
<body>
    <div class="alert-box">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    {% include "components/header.html" %}
    {% if username %}
        {{ username }}
    {% endif %}
    <main>
        <section>
            {% block content %}{% endblock %}
        </section>
        {% include "components/aside.html" %}
    </main>
    <hr>
    {% include "components/footer.html" %}
</body>
</html>

website/templates/base_aside.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='images/logo.jpg') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <script src="{{ url_for('static', filename='script.js') }}" defer></script>
    {% if title %}
        <title>{{ title }} - Chess Club IGS</title>
    {% else %}
        <title>Chess Club IGS</title>
    {% endif %}
</head>
<body>
    
    <div class="alert-box">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    {% include "components/header.html" %}
    {% if username %}
        {{ username }}
    {% endif %}
    <main>
        <section>
            {% block content %}{% endblock %}
        </section>
        {% include "components/aside.html" %}
    </main>
    <hr>
    {% include "components/footer.html" %}
</body>
</html>

website/templates/index.html
{% extends "base_aside.html" %}

{% block content %}
    <section class="hero-section">
        <div class="overlay">
            <aside style="align-items: center; margin: 0px auto;">
                <div class="welcome-message">
                    <h1 style="color: black;">Welcome to IGS Chess Club</h1>
                    <h5 style="color: black;">This website is a place for club members to compete against each other with their respective local ratings.</h5>
                    <h5 style="color: black;">Don't forget not to violate existing regulations.</h5>
                    <h5 style="color: black;">Enjoy!</h5>
                    <a href="https://www.instagram.com/chessclubigs" class="instagram-link" target="_blank">
                        <i class="fab fa-instagram"></i> Instagram
                    </a>
                </div>
            </aside>
            <!-- <h1>Welcome to IGS Chess Club</h1> -->
            <p>Compete, learn, and grow with fellow chess enthusiasts.</p>
            <a href="#team" class="cta-button">Meet Our Team</a>
        </div>
    </section>

    <div class="main-content-wrapper">
        <section class="introduction-section" id="team">
            <h2>Meet Our Team</h2>
            <div class="introduction-grid">
                <div class="intro-card">
                    <img src="{{ url_for('static', filename='images/mikel.jpg') }}" alt="Michael">
                    <h3>MichaelCh</h3>
                    <p>Our President!</p>
                    <a href="https://www.instagram.com/michaelch4n/" target="_blank">insta</a>
                </div>
                <div class="intro-card">
                    <img src="{{ url_for('static', filename='images/ezra.jpg') }}" alt="Ezra">
                    <h3>Ezra Azka</h3>
                    <p>Our Vice-President!</p>
                    <a href="#" target="_blank">insta</a>
                </div>
                <div class="intro-card">
                    <img src="{{ url_for('static', filename='images/fadel.jpg') }}" alt="Secretary">
                    <h3>Secretary</h3>
                    <p>Our Secretary!</p>
                    <a href="#" target="_blank">insta</a>
                </div>
                <div class="intro-card">
                    <img src="{{ url_for('static', filename='images/treasurer.jpg') }}" alt="Treasurer">
                    <h3>Treasurer</h3>
                    <p>Our Treasurer!</p>
                    <a href="#" target="_blank">insta</a>
                </div>
                <div class="intro-card">
                    <img src="{{ url_for('static', filename='images/publication.jpg') }}" alt="Publication">
                    <h3>Publication</h3>
                    <p>Our Publication Manager!</p>
                    <a href="#" target="_blank">insta</a>
                </div>
            </div>
        </section>

        <section class="puzzle-section">
            <h2>Chess Puzzle of the Day</h2>
            <div id="puzzle-container">
                <img src="{{ url_for('static', filename='images/kianachibi.jpg') }}" alt="Chess Puzzle">
            </div>
        </section>
    </div>
{% endblock content %}

website/templates/leaderboard-top-rated.html
{% extends "base_aside.html" %}

{% block content %}
    <div class="leaderboard-container">
        <h3>Top Rated</h3>
        <div class="leaderboards-list">
            <a href="{{ url_for('views.leaderboard_top_rated') }}">Top Rated</a>
            <a href="{{ url_for('views.leaderboard_win_rate') }}">Highest Win Rate</a>
            <a href="{{ url_for('views.leaderboard_tournaments_participated') }}">Most Tournaments Participated</a>
        </div>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Full Name</th>
                    <th>Rating</th>
                </tr>
            </thead>
            <tbody>
                {% set index = namespace(value=10*(page-1)) %}
                {% for member in members %}
                    {% set index.value = index.value + 1 %}
                    <tr>
                        <td>{{ index.value }}</td>
                        <td>{{ member.full_name }}</td>
                        <td>{{ member.rating }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="pagination-container">
            {% if members.has_prev %}
                <a href="{{url_for('views.leaderboard_top_rated', page=page-1)}}"></a>
            {% endif %}
            <p>Page {{ page }}</p>
            {% if members.has_next %}
                <a href="{{url_for('views.leaderboard_top_rated', page=page+1)}}"></a>
            {% endif %}
        </div>
    </div>
{% endblock content %}

website/templates/leaderboard-tournaments-participated.html
{% extends "base_aside.html" %}

{% block content %}
    <div class="leaderboard-container">
        <h3>Most Tournaments Participated</h3>
        <div class="leaderboards-list">
            <a href="{{ url_for('views.leaderboard_top_rated') }}">Top Rated</a>
            <a href="{{ url_for('views.leaderboard_win_rate') }}">Highest Win Rate</a>
            <a href="{{ url_for('views.leaderboard_tournaments_participated') }}">Most Tournaments Participated</a>
        </div>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Full Name</th>
                    <th>Tournaments</th>
                </tr>
            </thead>
            <tbody>
                {% set index = namespace(value=10*(page-1)) %}
                {% for member in members %}
                    {% set index.value = index.value + 1 %}
                    <tr>
                        <td>{{ index.value }}</td>
                        <td>{{ member.full_name }}</td>
                        <td>{{ member.tournaments | length }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="pagination-container">
            {% if members.has_prev %}
                <a href="{{url_for('views.leaderboard_tournaments_participated', page=page-1)}}"></a>
            {% endif %}
            <p>Page {{ page }}</p>
            {% if members.has_next %}
                <a href="{{url_for('views.leaderboard_tournaments_participated', page=page+1)}}"></a>
            {% endif %}
        </div>
    </div>
{% endblock content %}

website/templates/leaderboard-win-rate.html
{% extends "base_aside.html" %}

{% block content %}
    <div class="leaderboard-container">
        <h3>Highest Win Rate</h3>
        <div class="leaderboards-list">
            <a href="{{ url_for('views.leaderboard_top_rated') }}">Top Rated</a>
            <a href="{{ url_for('views.leaderboard_win_rate') }}">Highest Win Rate</a>
            <a href="{{ url_for('views.leaderboard_tournaments_participated') }}">Most Tournaments Participated</a>
        </div>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Full Name</th>
                    <th>Win Rate</th>
                </tr>
            </thead>
            <tbody>
                {% set index = namespace(value=10*(page-1)) %}
                {% for member in members %}
                    {% set index.value = index.value + 1 %}
                    <tr>
                        <td>{{ index.value }}</td>
                        <td>{{ member.full_name }}</td>
                        <td>{{ "%0.2f" % member.win_rate }}% <span style="color: chartreuse">{{ member.matches_won }}</span>|<span style="color: gray">{{ member.matches_drawn }}</span>|<span style="color: red">{{ member.matches_lost }}</span></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="pagination-container">
            {% if members.has_prev %}
                <a href="{{url_for('views.leaderboard_win_rate', page=page-1)}}"></a>
            {% endif %}
            <p>Page {{ page }}</p>
            {% if members.has_next %}
                <a href="{{url_for('views.leaderboard_win_rate', page=page+1)}}"></a>
            {% endif %}
        </div>
    </div>
{% endblock content %}

website/templates/login.html
{% extends "base.html" %}

{% block content %}
    <div class="form-container">
        <h1>Login</h1>
        <form action="" method="post">
            {{ form.hidden_tag() }}
            
            <div class="form-group">
                {{ form.username() }}
                {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>

            <div class="form-group">
                {{ form.password() }}
                {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>

            <div class="form-group">
                {{ form.submit() }}
            </div>
        </form>
    </div>
{% endblock content %}

website/templates/profile.html
{% extends "base.html" %}

{% block content %}
    profile
{% endblock content %}

website/templates/tournament.html
{% extends "base.html" %}

{% block content %}
    <div class="tournament-container">
        <div class="tournament-standings">
            <table>
                <thead>
                    <tr>
                        <th colspan="4"></th>
                        <th colspan="2">Score Based</th>
                        <th colspan="2">Rating Based</th>
                    </tr>
                    <tr>
                        <th></th>
                        <th>Full Name</th>
                        <th>Rating</th>
                        <th>Score</th>
                        <th>BHC1</th>
                        <th>BH</th>
                        <th>BHC1</th>
                        <th>BH</th>
                    </tr>
                </thead>
                <tbody>
                    {% for participant in tournament.participants %}
                    {% if loop.index % 2 == 0 %}
                        <tr style="background-color: white;">
                    {% else %}
                        <tr style="background-color: rgb(230, 230, 230);">
                    {% endif %}
                        <td>{{ loop.index }}</td>
                        <td>{{ participant.full_name }}</td>
                        <td>{{ participant.rating }}</td>
                        <td>{{ participant.score }}</td>
                        <td>{{ participant.bhc1 }}</td>
                        <td>{{ participant.bh }}</td>
                        <td>{{ participant.bhc1_rating }}</td>
                        <td>{{ participant.bh_rating }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

website/templates/tournaments-create.html
{% extends "base.html" %}

{% block content %}
    <div class="tournaments-create-container">
        <form action="{{ url_for("views.tournaments_create") }}" method="POST">
            {{ form.hidden_tag() }}
            
            <div class="form-group">
                <label for="title">Title:</label>
                {{ form.title(class="form-control", id="title") }}
                {% for error in form.title.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>
            
            <div class="form-group">
                <span>Time Control:</span>
                <label for="time-control-minutes"></label>
                {{ form.time_control_minutes(class="form-control", id="time-control-minutes") }}
                <label for="time-control-seconds"></label>
                {{ form.time_control_seconds(class="form-control", id="time-control-seconds") }}
                <label for="time-control-increment"></label>
                {{ form.time_control_increment(class="form-control", id="time-control-increment") }}
                {% for error in form.time_control_minutes.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
                {% for error in form.time_control_seconds.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
                {% for error in form.time_control_increment.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>
            
            <div class="form-group">
                <label for="pairing-system">Pairing System:</label>
                {{ form.pairing_system(class="form-control", id="pairing-system") }}
                {% for error in form.pairing_system.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>
            
            <div class="form-group">
                <label for="number-of-rounds">Number of Rounds:</label>
                {{ form.number_of_rounds(class="form-control", id="number-of-rounds") }}
                {% for error in form.number_of_rounds.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>

            <div class="form-group">
                <label for="participants">Participants:</label>
                <br>
                {{ form.participants(class="form-control", id="participants") }}
                {% for error in form.participants.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>
            
            <button type="submit" class="btn btn-primary">Create Tournament</button>
        </form>
    </div>

    {% block scripts %}
        <script>
            document.addEventListener("DOMContentLoaded", function() {
            const participantsSelect = document.getElementById("participants");

            let scrollPos = 0;
            participantsSelect.addEventListener("mousedown", function(event) {
                event.preventDefault();
                
                const targetIndex = event.target.index;
                const isSelected = this.options[event.target.index].selected;
                this.options[event.target.index].selected = !isSelected;
                this.focus();

                scrollPos = this.scrollTop;

                setTimeout(function() {
                    participantsSelect.scrollTop = scrollPos;
                });
            });
            participantsSelect.addEventListener("keydown", (event) => event.preventDefault());
        });
        </script>
    {% endblock scripts %}
{% endblock content %}

website/templates/tournaments.html
{% extends "base_aside.html" %}

{% block content %}
    <div class="tournaments-container">
        <div class="create-tournament-container">
            <a href="{{ url_for('views.tournaments_create') }}">
                <button class="create-tournament-button">
                    Create Tournament +
                </button>
            </a>
        </div>

        <h2>Ongoing</h2>
        <hr>
        <p>There are currently no tournaments running!</p>

        <h2>Archived</h2>
        <hr>
        <div class="tournaments-list-container">
            {% for tournament in tournaments %}
                <div class="tournaments_list_item">
                    <div class="tournaments_list_item_left">
                        <h3>{{ tournament.title }}</h3>
                        <p>Time Elapsed: {{ utils.format_time_delta_hours(utils.get_time_elapsed(tournament.tournament_date)) }}</p>
                        <p>No. of Participants: {{ tournament.participants | length }}</p>
                        <p>Running round {{ tournament.current_round }} out of {{ tournament.number_of_rounds }}</p>
                        <a href="{{ url_for('views.tournament', tournament_id=tournament.id) }}">View Standings</a>
                    </div>
                    <div class="tournaments_list_item_right">
                        <div class="tournaments_list_item_right_top">
                            <span class="tournament-date-text">{{ (utils.offset_time(tournament.tournament_date, timezone_offset)).strftime("%I:%M %p, %d/%m/%Y") }}</span>
                        </div>
                        <div class="tournaments_list_item_right_bottom">
                            <p class="pairing-system-text">{{ tournament.pairing_system }} <span><i class="fa-solid fa-user-group"></i></span></p>
                            <p class="time-control-format-text">{{ utils.get_time_control_format(tournament.time_control_duration, tournament.time_control_increment) }}</p>
                            <p class="time-control-type-text">
                                {% with type = utils.get_time_control_type(tournament.time_control_duration) %}
                                    {% if type == "Bullet" %}
                                        <span><i class="fa-solid fa-meteor"></i></span>
                                    {% elif type == "Blitz" %}
                                        <span><i class="fas fa-bolt"></i></span>
                                    {% elif type == "Rapid" %}
                                        <span><i class="fa-solid fa-hourglass-half"></i></span>
                                    {% else %}
                                        <span><i class="fa-solid fa-clock"></i></span>
                                    {% endif %}
                                    {{ utils.get_time_control_type(tournament.time_control_duration) }}</p>
                                {% endwith %}
                            <span>{{ tournament.time_control }}</span>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}